modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="hgf"
version="1.0.0"
displayName="hgf"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="maxim, MCreator"

[[dependencies.hgf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




